image: golang:1.12.4-alpine

stages:
  - build
  - test

before_script:
  - apk --update add git ca-certificates

build-code:
  stage: build
  script:
    - go mod download

test-code:
  stage: test
  script:
    - cd app && CGO_ENABLED=0 GOOS=linux go test ./...
    - go mod download
    - cmp go.mod go.sum~ >/dev/null 2>&1